title: Kyle Charlton
description: Software Developer
site_title: 'Kyle Charlton'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: kylejcharlton
email: kyle@kcharlton.dev

# absolute or relative
profile_picture: assets/images/pp.jpg
