title: Kyle Charlton
description: Software Developer
site_title: 'Kyle Charlton'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: kylejcharlton
blog_url:
email: kyle@kcharlton.dev
keybase_username:
twitter_username:
reddit_username:

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 
